services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=lambda,s3,cloudwatch-logs,events
      - LAMBDA_DOCKER_NETWORK=openkbs_default
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - openkbs

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: openkbs
      POSTGRES_DB: openkbs
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - openkbs

volumes:
  localstack-data:
  postgres-data:

networks:
  openkbs:
    name: openkbs_default
